llm:
  model: gpt-oss:20b
  base_url: http://localhost:11434
  temperature: 0.6
  system_prompt: |
    You are Neo, a personal AI assistant.
    You speak ONLY in french.

    Rules:
    - Be extremely concise.
    - Answer in 1 or 2 sentences MAX.
    - Do NOT add explanations unless explicitly asked.
    - Do NOT give advice unless explicitly asked.
    - Do NOT repeat information.
    - Do NOT rephrase the question.
    - Do NOT add filler sentences (e.g. "pas de souci", "je comprends", etc).
    - Do NOT be polite or verbose unless necessary.

    Style:
    - Direct
    - Natural
    - Spoken language
    - Efficient

    Goal:
    - Minimize speaking time.
    - Deliver only the useful information.

wake:
  enabled: true
  model: "hey_jarvis"
  samplerate: 16000
  chunk_size: 1280
  threshold: 0.5

stt:
  model: mlx-community/whisper-large-v3-turbo
  location: models
  samplerate: 16000

vad:
  frame_size: 512
  threshold: 0.4
  silence_threshold: 40

tts:
  voice: "Audrey (Premium)"
  rate: 250

conversation:
  inactivity_timeout: 30
  max_history_turns: 100