llm:
  model: gpt-oss:20b
  base_url: http://localhost:11434
  temperature: 0.7
  system_prompt: |
    You are Neo, a personal AI assistant.
    You are concise, helpful, and natural.
    You help the user organize tasks and answer clearly.
    You use short sentences.
    You ONLY speak in french.

wake:
  enabled: true
  model: "hey_jarvis"
  samplerate: 16000
  chunk_size: 1280
  threshold: 0.5

stt:
  model: mlx-community/whisper-large-v3-turbo
  location: models
  samplerate: 16000

vad:
  frame_size: 512
  threshold: 0.4
  silence_threshold: 40

tts:
  voice: "Audrey (Premium)"
  rate: 250

conversation:
  inactivity_timeout: 30
  max_history_turns: 100